config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end

  root 'tops#index'
  resources :tops, only: :index
  resources :articles, only: [:new, :create]
  resources :my_pages, only: :index
  namespace :api, {format: 'json'} do
    namespace :v1 do
      resources :articles, only: [:index, :show, :create]
      resources :my_pages, only: [:index, :destroy]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Infoadmin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://unpkg.com/vue@next" defer></script>
    <link href="https://fonts.googleapis.com/earlyaccess/hannari.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="<%= body_class %>">
    <div class="wrapper">
      <header>
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <%= link_to '日記帳', tops_path, class: 'navbar-brand' %>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <% if user_signed_in? %>
                <i class="fas fa-sticky-note" style="line-height:43px;"></i>
                  <li class="nav-item active">
                    <%= link_to '投稿する', new_article_path, class: 'nav-link' %> <span class="sr-only">(current)</span>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'マイページ', my_pages_path, class: 'nav-link' %>
                  </li>
                <% end %>
                <% if user_signed_in? %>
                  <li class="nav-item dropdown">
                    <div class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <%= current_user.last_name %>
                    </div>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <%= link_to 'プロフィール変更', edit_user_registration_path, class: "dropdown-item" %>
                      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                    </div>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to 'サインアップ', new_user_registration_path, class: 'nav-link' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %>
                  </li>
                <% end %>
              </ul>
            </div>
          </nav>
        </div>
      </header>
      <div class="container">
        <div class="main">
          <% if notice.present? %>
            <div class="alert alert-success" role="alert"><%= notice %></div>
          <% elsif alert.present? %>
            <div class="alert alert-warning" role="alert"><%= alert %></div>
          <% end %>
          <%= yield %>
        </div> <!-- main -->
      </div> <!-- container -->
    </div> <!-- wrapper -->
  </body>
</html>